# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(verbose_name='%m-%d-%y'),
        ),
    ]
