# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_author_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='authors notes'),
            preserve_default=False,
        ),
    ]
